language: ruby
rvm:
  - 2.1.0
  - 2.0.0
  - 1.9.3
  - 1.9.2
  - 1.8.7
  - jruby-18mode
  - jruby-19mode
  - rbx-2
  - ree
notifications:
  email:
    recipients:
      - grey@gocardless.com
script: bundle exec rspec spec
